replicaCount: 1

appPort: 5000

image:
  registry: harbor.localhost.com/gustavome/sample-app
  tag: latest

environmentVariables:
  - name: MONGODB_DB
    value: api
  - name: MONGODB_HOST
    value: sample-app-ci-mongodb
  - name: MONGODB_USERNAME
    value: api
  - name: MONGODB_PASSWORD
    value: api

livenessProbe: {}

readinessProbe: {}

ingress:
  enabled: false

mongodb:
  auth:
    usernames:
      - api
    passwords:
      - api
    databases:
      - api
